# Generated by Django 3.2.6 on 2022-04-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220406_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
    ]
